---

# Put any environment-specific vars here that are NOT sensitive

remote_username: "{{ vault_deploy_username }}"
phoenix_otp_app_name: example_app
static_app_files_path_local: ~/test_repos/starter_frontend/build/
deploy_directory: "/var/www/app_frontend/"