---

vault_ssl_email: myemail@example.com # Replace with a real, valid email address that you own
vault_ssl_domain_name: example.com # Replace with the domain name you obtained and setup for this server