---

- name: Setup Ubuntu server with PostgreSQL, Nginx, SSL, UFW for use with Phoenix app
  hosts: all
  remote_user: root
  become: yes

  # pre_tasks:
    # - name: Log system_users
    #   debug:
    #     msg: "Test system users: {{ system_users }}"

  #   - name: Log test deploy user
  #     debug:
  #       msg: "Test deploy user: {{ test_deploy_username }}"

  #   - name: Log test vault deploy user
  #     debug:
  #       msg: "Test Vault deploy user: {{ test_vault_deploy_username }}"

  roles:
    # - common 
    - cmcdonald82.users_role
    - cmcdonald82.postgresql_role
    - cmcdonald82.ssl_role
    - cmcdonald82.nginx_role
    - cmcdonald82.environment_role
    - cmcdonald82.firewall_role
    - cmcdonald82.server_security_role