---

- name: Setup Ubuntu server with PostgreSQL, Nginx, SSL, UFW for use with Phoenix app
  hosts: all
  remote_user: "{{ remote_username }}"
  become: yes

  roles:
    - cmcdonald82.users_role
    - cmcdonald82.postgresql_role
    - cmcdonald82.ssl_role
    - cmcdonald82.nginx_role
    - cmcdonald82.environment_role
    - cmcdonald82.firewall_role
    - cmcdonald82.server_security_role