---

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    # - fail2ban # now included in ansible-role-server-security
    # - ufw # now included in ansible-role-firewall
