---

# Place non-sensitive variables specific to the postgresql role here 

# postgresql_version: 10 # Postgres 10 seems to have connection issues - try to figure out why. Maybe due to requiring encrypted passwords in version 10? UPDATE: This issue is fixed as long as postgrex version 0.13.5 is used instead of 0.13.4

postgresql_databases: 
  - name: "{{ vault_postgresql_db_name }}"

postgresql_users: 
  - name: "{{ vault_deploy_username }}"
    password: "{{ vault_postgresql_db_password }}" 
    encrypted: yes
    db: "{{ vault_postgresql_db_name }}"
    role_attr_flags: "SUPERUSER,LOGIN"

postgresql_hba_entries: 
  - type: local
    user: "{{ vault_deploy_username }}"
    method: md5
    database: all 
