---

environment_vars:
  REPLACE_OS_VARS: true
  DB_NAME: "{{ vault_postgresql_db_name }}"
  DB_USERNAME: "{{ vault_postgresql_db_username }}"
  DB_PASSWORD: "{{ vault_postgresql_db_password }}"
  DB_HOSTNAME: "{{ vault_postgresql_db_hostname }}"
  SECRET_KEY_BASE: "{{ vault_environment_secret_key_base }}"
  DOMAIN_NAME: "{{ ssl_domain_name }}"
  PORT: 4000
  PHOENIX_APP_NAME: starter
  COOKIE: "{{ vault_environment_cookie }}" 
